#Machine Learning Pipline

Read --> Split --> Divide --> Train --> Predict --> Evaluate

In [19]:
import numpy as np
import pandas as pd

data ={
    "area":[100, 150, 200, 250, 300],
    "bedrooms":[2, 3, 3, 4, 5],
    "age":[20, 15, 10, 5, 2],
    "price":[200, 300, 400, 500, 650]
}
df = pd.DataFrame(data)
df.to_csv("housing.csv", index=False)

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

##Step1. Reading the data

In [21]:
df = pd.read_csv("housing.csv")
df.head()

   area  bedrooms  age  price
0   100         2   20    200
1   150         3   15    300
2   200         3   10    400
3   250         4    5    500
4   300         5    2    650

##Step2. Seperate the features and the label

In [22]:
x = df[["area", "bedrooms", "age"]]
y = df["price"]

##Step3. Split the data

In [23]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

##Step4. Train model
###Step4.1 Create model
###Step4.2 Fit model

In [24]:
model = LinearRegression()

In [25]:
model.fit(x_train, y_train)

LinearRegression()

#Step5. Predict

In [26]:
y_pred = model.predict(x_test)

#Step6. Evaluate

In [27]:
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("RMSE: ", rmse)

mse = mean_squared_error(y_test, y_pred)
print("MSE: ", mse)

r2=r2_score(y_test, y_pred)
print("R2: ", r2)

RMSE:  2.2737367544323206e-13
MSE:  5.169878828456423e-26
R2:  nan

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

#ML Pipline for linear classification

In [28]:
import numpy as np
import pandas as pd

data ={
    "hours_studied":[2, 3, 4, 5, 6, 7, 8, 9],
    "attendance":[50, 60, 70, 80, 85, 90, 95, 100],
    "passed":[0, 0, 0, 1, 1, 1, 1, 1],
}
df = pd.DataFrame(data)
df.to_csv("students_csv", index=False)

In [29]:
df = pd.read_csv("students_csv")
df.head()

   hours_studied  attendance  passed
0              2          50       0
1              3          60       0
2              4          70       0
3              5          80       1
4              6          85       1

In [30]:
x = df[["hours_studied", "attendance"]]
y = df["passed"]

In [31]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [32]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [33]:
model.fit(x_train, y_train)

LogisticRegression()

In [35]:
y_pred = model.predict(x_test)

In [36]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1_score = f1_score(y_test, y_pred)
print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("F1 Score: ", f1_score)

Accuracy:  1.0
Precision:  1.0
Recall:  1.0
F1 Score:  1.0